### ISSUE TITLE
Meditation types

### ISSUE THREAD

**Issue by jessewillems1995** [dliedke/Meditate#4]
Hi,

Thanks so much for this app, I use it frequently. Research has shown that the type of meditation matters quite a lot on the specific effect it will have over time. It would be amazing if you can create activity types that we can give our own name based on the technique used (e.g. Yoga Nidra, Samadhi, Vipassana). 

Furthermore, if I select a 1 hour session, but save it after 50 minutes, the activity name will still save as "meditation 1 hr".

Hope you can look into this!

Thanks,

Jesse

**Comment by dliedke** [comment]
Hello @jessewillems1995, really appreciate your feedback. Indeed, meditation is amazing to improve mental health.

About your points:

Activity name is kind of tricky because we have a hard limit of around 32 chars when saving from API. It is a nice idea, but most people don't even custom configure the sessions.

For the activity name with incorrect name this can't be fixed, unfortunately, I tried hard this long time ago. The activity name provided when start the recording can't be changed later, unless saved and changed in Garmin Connect. I know this is kind of a pain, but the API doesn't allow changing it when stop recording. 

Thank you!

Daniel Liedke
